Repository dmuhs/pythx, pull requests merged in 2019-04, with the labels that each got.

#20 Update analysis issues response domain model
  pythx/cli/main.py
  pythx/models/response/__init__.py
  pythx/models/response/detected_issues.py
  tests/common.py
  tests/test_api_handler.py
  tests/test_client.py
  tests/test_detected_issues_response.py
Labels: Priority: Critical, Status: In Progress, Type: Bug

#24 Add mainSource param to analyze method
  pythx/api/client.py
  pythx/models/request/analysis_submission.py
  pythx/models/request/schema/analysis-submission.json
  tests/common.py
  tests/test_analysis_submission_request.py
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#25 Add middleware shortcut to client
  README.rst
  pythx/api/client.py
  pythx/api/handler.py
  pythx/cli/main.py
  pythx/cli/utils.py
  pythx/models/request/analysis_list.py
  pythx/models/request/base.py
  pythx/models/response/analysis.py
  pythx/models/response/base.py
  tests/common.py
  tests/test_analysis.py
  tests/test_analysis_list_request.py
  tests/test_analysis_list_response.py
  tests/test_analysis_status_request.py
  tests/test_analysis_status_response.py
  tests/test_analysis_submission_request.py
  tests/test_analysis_submission_response.py
  tests/test_api_handler.py
  tests/test_auth_login_request.py
  tests/test_auth_login_response.py
  tests/test_auth_logout_request.py
  tests/test_auth_logout_response.py
  tests/test_auth_refresh_request.py
  tests/test_auth_refresh_response.py
  tests/test_client.py
  tests/test_client_tool_name_middleware.py
  tests/test_config.py
  tests/test_detected_issues_request.py
  tests/test_detected_issues_response.py
  tests/test_issue.py
  tests/test_model_validator_errors.py
  tests/test_nocache_middleware.py
  tests/test_oas_request.py
  tests/test_oas_response.py
  tests/test_util_methods.py
  tests/test_version_request.py
  tests/test_version_response.py
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#27 Add main source support to CLI
  pythx/cli/main.py
  pythx/cli/opts.py
  pythx/cli/utils.py
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance
